// Generated by nuxt-robots
declare module 'nitropack' {
  interface PrerenderRoute {
    _sitemap?: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapUrl
  }
  interface NitroRouteRules {
    index?: boolean
    sitemap?: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
  }
  interface NitroRuntimeHooks {
    'sitemap:index-resolved': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapIndexRenderCtx) => void | Promise<void>
    'sitemap:input': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapInputCtx) => void | Promise<void>
    'sitemap:resolved': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapOutputHookCtx) => void | Promise<void>
    'sitemap:sources': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapSourcesHookCtx) => void | Promise<void>
  }
}
declare module 'nitropack/types' {
  interface PrerenderRoute {
    _sitemap?: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapUrl
  }
  interface NitroRouteRules {
    index?: boolean
    sitemap?: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
  }
  interface NitroRuntimeHooks {
    'sitemap:index-resolved': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapIndexRenderCtx) => void | Promise<void>
    'sitemap:input': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapInputCtx) => void | Promise<void>
    'sitemap:resolved': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapOutputHookCtx) => void | Promise<void>
    'sitemap:sources': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapSourcesHookCtx) => void | Promise<void>
  }
}
declare module 'vue-router' {
    interface RouteMeta {
        sitemap?: import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.3.5_vite@7.1.5_@types+node@24.4.0_jiti@2.5.1_7a988ff6449352c775573db224d6d9cb/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
    }
}

export {}
