// Generated by nuxt-robots

import type { RobotsContext } from '#robots/types'

declare module 'nitropack/types' {
  interface NitroApp {
    _robots: {
      ctx: import('../../../../node_modules/.pnpm/@nuxtjs+robots@5.5.5_h3@1.15.4_magicast@0.3.5_vue@3.5.21_typescript@5.9.2_/node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsConfigContext
      nuxtContentUrls?: Set<string>
    },
    _robotsRuleMatcher: (url: string) => any
    _robotsPatternMap?: Map<string, import('../../../../node_modules/.pnpm/@nuxtjs+robots@5.5.5_h3@1.15.4_magicast@0.3.5_vue@3.5.21_typescript@5.9.2_/node_modules/@nuxtjs/robots/dist/runtime/types').PatternMapValue>
  }
  interface NitroRouteRules {
    robots?: import('../../../../node_modules/.pnpm/@nuxtjs+robots@5.5.5_h3@1.15.4_magicast@0.3.5_vue@3.5.21_typescript@5.9.2_/node_modules/@nuxtjs/robots/dist/runtime/types').RobotsValue | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRouteConfig {
    robots?: import('../../../../node_modules/.pnpm/@nuxtjs+robots@5.5.5_h3@1.15.4_magicast@0.3.5_vue@3.5.21_typescript@5.9.2_/node_modules/@nuxtjs/robots/dist/runtime/types').RobotsValue | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRuntimeHooks {
    'robots:config': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+robots@5.5.5_h3@1.15.4_magicast@0.3.5_vue@3.5.21_typescript@5.9.2_/node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsConfigContext) => void | Promise<void>
    'robots:robots-txt': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+robots@5.5.5_h3@1.15.4_magicast@0.3.5_vue@3.5.21_typescript@5.9.2_/node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsTxtContext) => void | Promise<void>
  }
}

declare module 'nitropack' {
  interface NitroApp {
    _robots: {
      ctx: import('../../../../node_modules/.pnpm/@nuxtjs+robots@5.5.5_h3@1.15.4_magicast@0.3.5_vue@3.5.21_typescript@5.9.2_/node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsConfigContext
      nuxtContentUrls?: Set<string>
    },
    _robotsRuleMatcher: (url: string) => any
    _robotsPatternMap?: Map<string, import('../../../../node_modules/.pnpm/@nuxtjs+robots@5.5.5_h3@1.15.4_magicast@0.3.5_vue@3.5.21_typescript@5.9.2_/node_modules/@nuxtjs/robots/dist/runtime/types').PatternMapValue>
  }
  interface NitroRouteRules {
    robots?: import('../../../../node_modules/.pnpm/@nuxtjs+robots@5.5.5_h3@1.15.4_magicast@0.3.5_vue@3.5.21_typescript@5.9.2_/node_modules/@nuxtjs/robots/dist/runtime/types').RobotsValue | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRouteConfig {
    robots?: import('../../../../node_modules/.pnpm/@nuxtjs+robots@5.5.5_h3@1.15.4_magicast@0.3.5_vue@3.5.21_typescript@5.9.2_/node_modules/@nuxtjs/robots/dist/runtime/types').RobotsValue | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRuntimeHooks {
    'robots:config': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+robots@5.5.5_h3@1.15.4_magicast@0.3.5_vue@3.5.21_typescript@5.9.2_/node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsConfigContext) => void | Promise<void>
    'robots:robots-txt': (ctx: import('../../../../node_modules/.pnpm/@nuxtjs+robots@5.5.5_h3@1.15.4_magicast@0.3.5_vue@3.5.21_typescript@5.9.2_/node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsTxtContext) => void | Promise<void>
  }
}

declare module 'h3' {
  interface H3EventContext {
    robots: RobotsContext
  }
}

export {}
